name: Deploy Website

on:
  push:
    branches:
      - main

env:
  SURGE_DOMAIN_STORE: ${{ secrets.SURGE_DOMAIN_STORE }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying apps
    steps:
      - uses: actions/checkout@v3 # checkout whatever branch the PR is using
        with:
          fetch-depth: 0
      - run: npm i --legacy-peer-deps
      - run: npx nx affected --target=deploy --base=HEAD~1 --parallel
